### ISSUE TITLE
[question] importing modules in staticmodules

### ISSUE THREAD

**Issue by tlienart** [MasonProtter/StaticModules.jl#3]
you say explicitly in the readme that static modules don't support 'using', I'm wondering whether there's any path to importing foreign code in a static module as that would something I'd find quite helpful.

For context in Franklin.jl pages with Julia code have the code executed in a module that's tied to the page; it's the same idea (I think) as the static module except that it's not as clean and it's a full module so import statements will work. 
It might improve overall code quality if I were to use something dedicated instead of my own soup but I'd need to be able have import statements. 

Is this impossible due to the way it's constructed and the only way is effectively having a full module?

I could see Weave being interested in this too (the above mentioned soup is adapted from Weave code).

**Comment by MasonProtter** [comment]
Hm, I'm not sure I've thought about this enough to have a good response. One idea that comes to mind is to make a `@using` macro for use inside a StaticModule, but only works on packages that have already been `import`ed. 

e.g. you could have something like 
```julia
using StaticModules
import StaticArrays

@staticmodule Foo begin
    @using StaticArrays
    SA[1 2]
end
```
which would get turned into
```julia
@staticmodule Foo begin
    SA = StaticArrays.SA
    SVector = StaticArrays.SVector
    ...
    SA[1 2]
end
```

**Comment by tlienart** [comment]
That would be quite nice yes!

**Comment by MasonProtter** [comment]
One concern I'd have is that since a `StaticModule` wraps a `NamedTuple`, we might start running into the problems inherent with large tuples if a package exports too many names.

**Comment by tlienart** [comment]
would this be solved if we only used an `@import` macro? possibly with explicit names like `@import StaticArrays: SA` ?

**Comment by MasonProtter** [comment]
Hm, the `@unpack` macro from Parameters.jl is basically what we want actually. 
```julia
julia> using Parameters, StaticModules; import StaticArrays

julia> @staticmodule Foo begin
           @unpack SA, SVector = StaticArrays
           v = SA[1,2,3]
       end
StaticModule Foo containing
  SVector = SArray{Tuple{S},T,1,S} where T where S
  v       = [1, 2, 3]
  SA      = SA
  ##253   = StaticArrays

```

**Comment by MasonProtter** [comment]
I kinda like the name `@unpack` for this because it makes it clear that the macro isn't actually going to import `StaticArrays` if it's not already present.

I could just add a dependency on Parameters.jl and provide `@unpack` if that would be helpful to you.

**Comment by tlienart** [comment]
That's great! No I think your example is perfect maybe it doesn't need to be in especially if ultimately your macro gets integrated in Parameters :)

Thanks for this!

**Comment by MasonProtter** [comment]
I put a note into the `README` about this, thanks for bringing it up. https://github.com/MasonProtter/StaticModules.jl#replacements-for-using
